name = "DPFEHM"
uuid = "8c3ed914-120a-47bd-8d72-56c743732853"
authors = ["Daniel O'Malley <omalled@lanl.gov>"]
version = "0.1.0"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentiableBackwardEuler = "f6d13b3e-c4dc-4f43-9d3d-672a47390f59"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearEquations = "dcda4a48-b9f7-11e9-2d4a-7da573938c24"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.7"
AlgebraicMultigrid = "0.5"
ChainRulesCore = "1.14"
DifferentiableBackwardEuler = "0.1"
ForwardDiff = "0.10"
Interpolations = "0.13"
NLsolve = "4.5"
NonlinearEquations = "0.1"
StaticArrays = "1.3"
Zygote = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
